package com.dailydiary

import android.app.NotificationManager
import android.content.Context
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import java.text.SimpleDateFormat
import java.util.*

/**
 * WorkManager worker that runs nightly to:
 * 1. Collect all transcriptions from the day
 * 2. Send them to AI for summarization
 * 3. Email the diary entry
 * 4. Clean up old data
 */
class DailySummaryWorker(
    appContext: Context,
    workerParams: WorkerParameters
) : CoroutineWorker(appContext, workerParams) {

    companion object {
        private const val TAG = "DailySummaryWorker"
        private const val SUMMARY_NOTIFICATION_ID = 100
    }

    override suspend fun doWork(): Result {
        Log.d(TAG, "Starting daily summary generation")

        try {
            val transcriptionManager = TranscriptionManager(applicationContext)
            val aiSummarizer = AISummarizer(applicationContext)
            val emailSender = EmailSender(applicationContext)

            val dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.US)
            val displayDateFormat = SimpleDateFormat("EEEE, MMMM d, yyyy", Locale.US)
            val today = dateFormat.format(Date())
            val displayDate = displayDateFormat.format(Date())

            // Get formatted transcriptions
            val transcriptions = transcriptionManager.getFormattedTranscriptionsForDate(today)

            if (transcriptions.isBlank()) {
                Log.d(TAG, "No transcriptions for today. Skipping summary.")
                showNotification("Daily Diary", "No voice recordings captured today.")
                return Result.success()
            }

            // Generate AI summary
            Log.d(TAG, "Generating AI summary...")
            val summary = aiSummarizer.generateSummary(transcriptions, displayDate)

            // Send email
            val subject = "📔 Daily Diary - $displayDate"
            val emailBody = buildString {
                appendLine(summary)
                appendLine()
                appendLine("---")
                appendLine("Generated by Daily Diary App")
                appendLine("Date: $displayDate")
            }

            val emailSent = emailSender.sendDiarySummary(subject, emailBody)

            if (emailSent) {
                showNotification(
                    "Daily Diary Summary Sent! 📔",
                    "Your diary entry for $displayDate has been emailed."
                )
                Log.d(TAG, "Daily summary sent successfully")
            } else {
                showNotification(
                    "Daily Diary ⚠️",
                    "Summary generated but email failed. Check email settings."
                )
                Log.w(TAG, "Summary generated but email sending failed")
            }

            // Cleanup old transcriptions (keep 30 days)
            transcriptionManager.cleanupOldData(30)

            return Result.success()
        } catch (e: Exception) {
            Log.e(TAG, "Error generating daily summary", e)
            showNotification("Daily Diary Error", "Failed to generate summary: ${e.message}")
            return Result.retry()
        }
    }

    private fun showNotification(title: String, text: String) {
        val notification = NotificationCompat.Builder(applicationContext, DailyDiaryApp.CHANNEL_ID_SUMMARY)
            .setSmallIcon(android.R.drawable.ic_dialog_email)
            .setContentTitle(title)
            .setContentText(text)
            .setStyle(NotificationCompat.BigTextStyle().bigText(text))
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .setSilent(true)
            .setAutoCancel(true)
            .build()

        val notificationManager = applicationContext.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        notificationManager.notify(SUMMARY_NOTIFICATION_ID, notification)
    }
}
